<?php
include 'db_connection.php';

$product_id = "";       // This should ideally be auto-generated by the database
$pname = "";
$desc = "";
$rprice = "";
$bprice = "";
$qty = "";
$supplier = "";
$supplierId = "";
$wareloc = "";
$dob = "";
$dateLoggedIn = "";

// Check if the form was submitted
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    // Retrieve form data
    $pname = $_POST['pname'];
    $desc = $_POST['desc'];
    $rprice = $_POST['rprice'];
    $bprice = $_POST['bprice'];
    $qty = $_POST['qty'];
    $supplier = $_POST['supplier'];
    $supplierId = "ID_" . strtoupper(substr($supplier, 9, 1)); // Example: creating supplier ID based on supplier name
    $wareloc = $_POST['wareloc'];
    $dob = $_POST['dob'];
    $dateLoggedIn = date('Y-m-d H:i:s'); // Current date and time
	
// SQL to create Product table
$sql = "CREATE TABLE IF NOT EXISTS Product (
    id INT AUTO_INCREMENT PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    description TEXT,
    retail_price DECIMAL(10, 2) NOT NULL,
    buy_price DECIMAL(10, 2) NOT NULL,
    quantity INT NOT NULL,
    supplier VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)";

if ($conn->query($sql) === TRUE) {
    echo "Table 'Product' created successfully.";
} else {
    echo "Error creating table: " . $conn->error;
}

// Close the connection
$conn->close();
?>
